version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/fleet-api/
  - source: /navigation.png
    destination: /var/www/fleet-api/
permissions:
  - object: /var/www/fleet-api/
    pattern: “**”
    owner: ubuntu
    group: utuntu
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

