#!/bin/bash

export PATH=/home/ubuntu/.rvm/gems/ruby-2.6.5/bin:/home/ubuntu/.rvm/gems/ruby-2.6.5@global/bin:/home/ubuntu/.rvm/rubies/ruby-2.6.5/bin:/home/ubuntu/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ubuntu/.rvm/bin:/home/ubuntu/.rvm/bin
sudo kill -9 $(cat /var/www/fleet-api/tmp/pids/server.pid)

# Remove if previous deployment folder exists
rm -rf /var/www/fleet-api

# Create new deployment folder and make nginx owner
mkdir /var/www/fleet-api

sudo apt install -y curl
sudo apt-get install -y apache2
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt-get update -y
sudo apt-get install  -y git-core zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev software-properties-common libffi-dev nodejs yarn

sudo apt-get install -y libgdbm-dev libncurses5-dev automake libtool bison libffi-dev
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
curl -sSL https://get.rvm.io | bash -s stable
source ~/.rvm/scripts/rvm
rvm install -y 2.6.5
rvm use 2.6.5 --default
ruby -v

#add feature
gem install bundler — user-install
gem install -y rails -v 6.0.3.4
sudo apt-get -y install libqt4-dev libqtwebkit-dev
sudo apt-get install -y qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
sudo apt-get install -y cmake
sudo apt install -y redis-server
sudo apt-get install -y imagemagick
sudo apt-get install -y libxslt-dev libxml2-dev zlib1g-dev
gem install bundler — user-install

# Go to the deployment directory
cd /var/www/fleet-api/
bundle install
